site_name: English 21w13a
site_author: BSOD
site_description: 学习资料，真的是学习资料，别乱想！
copyright: Made with ♥ in Shanghai<br/>Copyright © 2021 BSOD<br/>Deploy by Github Pages & Vercel
theme:
  name: material
  language: zh
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github-alt
repo_url: https://github.com/BSOD-qian/eng
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.tabbed
  - footnotes
plugins:
  - search